### ISSUE TITLE
Fatal error: MySQL DB

### ISSUE THREAD

**Issue by ve3lst** [hernantas/MangaReader#66]
Hi,

I've been trying to install MangaReader on my local web-server (XAMPP) but it there's error connecting to the DB.

The user name and password is absolutely right, I've successfully imported manga.sql into a DB called manga, and ofcorse I changed $CFG['MANGA_PATH'] to my location.

Also I'm using MySQL on port 3308 so I added ":3308" to $CFG['MANGA_PATH']

But it didn't work and give me the following error

> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\MangaReader\system\db.php:18 Stack trace: #0 C:\xampp\htdocs\MangaReader\system\db.php(50): DB->__construct('manga', '127.0.0.1:3308', 'root', '') #1 C:\xampp\htdocs\MangaReader\config.php(23): include('C:\xampp\htdocs...') #2 C:\xampp\htdocs\MangaReader\index.php(3): include('C:\xampp\htdocs...') #3 {main} thrown in C:\xampp\htdocs\MangaReader\system\db.php on line 18

I thought it may because my DB doesn't have a password so I tried adding a new user with password but it didn't work

What I'm supposed to do?

Thanks!

![screenshot from 2016-08-26 23-16-02](https://cloud.githubusercontent.com/assets/18611574/18019436/c22ad64a-6be4-11e6-8f76-5f872e1f820b.png)
![screenshot from 2016-08-26 23-15-03](https://cloud.githubusercontent.com/assets/18611574/18019440/c3923492-6be4-11e6-964f-ca9eb99d121f.png)
![screenshot from 2016-08-26 23-12-20](https://cloud.githubusercontent.com/assets/18611574/18019441/c45567be-6be4-11e6-9da6-f9baba3981b4.png)

**Comment by hernantas** [comment]
I think this is an issue with your XAMPP installation. Your PHP doesn't have MySQL extension module installed or loaded.

Some solution:
- Look at your `php.ini` in xampp, find or add this line if not exists `extension=php_mysql.dll`
- or delete the old one and install the latest XAMPP
- or wait for the new version

This is an old project that I develop when still in high school and in this version I use MySQL. MySQL is old, has many issues with it and it recommended to avoid using this in latest development practice. 

I make the new version of this web application that has better performance and more feature like installation page (so you don't have to do it manually, just plug and play), automatic scan, etc. 
But it not done yet and I don't have any ETA. I try my best to make the new version as fast as I can since I use this web app to read my manga collection too. Sorry for this...

**Comment by hernantas** [comment]
No longer valid, this is for the old version
