### ISSUE TITLE
After scanning the DIR.It's occurred some errors...

### ISSUE THREAD

**Issue by Asteriska001** [hernantas/MangaReader#73]
Hi bro,
 After scanning my DIR,it's show "Scan completed",but It's occurred some errors in these tags as
"Manga directory " "Popular Manga" "Lastest Updates"...
 Like this..
  
![image](https://user-images.githubusercontent.com/15817126/50735399-6a4d1700-11e9-11e9-8bed-53b2ea80b19d.png)
 
My data's structure like this:
![image](https://user-images.githubusercontent.com/15817126/50735464-83a29300-11ea-11e9-8e04-0550bc9af8ad.png)

But I can still view the comic normally in the "Home"..
![image](https://user-images.githubusercontent.com/15817126/50735422-bef09200-11e9-11e9-9fb0-059d6af2a340.png)
![image](https://user-images.githubusercontent.com/15817126/50735423-d16acb80-11e9-11e9-9d06-14b5cf9c678f.png)

I'd appreciate it if you can help me with the problem.By the way,This project is splendid..I like it so much :)

**Comment by hernantas** [comment]
Hey, sorry late reply. So muich things to do in this new year (I haven't event have my holiday yet)

This caused by your php settings to display all kind of message (notice, warning, error). The message in your ss is not error, and it's not harmful. Just notice that I don't declare my variable and I don't even understand why php dev show it.

Anyway, if you want to remove them, there are couple way to do that:
**1. Disable notice in  PHP.ini**
Open php.ini -> Change display_errors to 0

**2. Add this line to index.php**
    This will remove unimportant message
        `error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);`
    Or this will remove all message, including error
        `error_reporting(0);`
Place this anywhere in `index.php` after `<?php` and before `?>` tag, **choose 1**

I hope it will fix your problem. Cheers...

**Comment by Asteriska001** [comment]
Yeah..I fixed it successfully. Thanks!  
  But there is a problem occurred when I set up the project at my LiunxServer,too. (I set up the project in the Win with XAMPP at first ) 
 Like this:
   
![image](https://user-images.githubusercontent.com/15817126/50878146-37d13300-1410-11e9-938d-3ee33e9a094c.png)
 Once logged in,the page still stayed in the index page..It;s no change.happened.
 And the "Sign in/Sign up" button can't react my click..It's no responding..The page didn't change.

I checked my apache''s error log.It's seems everything is fine..Could you give me some suggestions?
And I've sent a mail including my server's ip,you could access it to know my situation clearly..

**Comment by hernantas** [comment]
I haven't got any of your email, did you send it to the correct address?

From your screenshot above, it seems that the url path is not set correctly. Can you make sure that your htaccess is enabled in your server settings?

Find this line in your server settings `httpd.conf`:
`
<Directory "/var/www">
    AllowOverride All
</Directory>
`

This project require the server to allow htaccess override to make the URL path like this `localhost/manga/directory` or `localhost/manga/id/55123` instead of `localhost/manga?path=directory` or `localhost/manga?id=55123`

or refer to this link for more info about enabling htaccess https://askubuntu.com/questions/429869/is-this-a-correct-way-to-enable-htaccess-in-apache-2-4-7

**Comment by Asteriska001** [comment]
I sent mail to the "business@hernantas.com",It failed.So i sent to the "hernantas@gamil.com".And i set the htaccess normally..

**Comment by hernantas** [comment]
So, is it fixed?

**Comment by Asteriska001** [comment]
Yeah..The "notice error" fixed,but the "button error" isn't.

**Comment by Asteriska001** [comment]
Did you received the message about "ip"?

**Comment by hernantas** [comment]
Yeah, I have received. I have accessed your website, it seems that the image is not pulled from git lfs, how did you upload it to your site? Did you also use `git lfs get`

**Comment by Asteriska001** [comment]
this is a lightly error..You can try to git clone your project.The image error will happen. I don't know the reason,

**Comment by Asteriska001** [comment]
Don't mind it.Not a big deal.

**Comment by hernantas** [comment]
Nah, don't worry. Now I know why your image is like that. It just that the images is not pulled from git lfs.
Try to clone this repository using `git lfs clone`

If you try to open the image in text editor, it may contain:
`
version https://git-lfs.github.com/spec/v1
oid sha256:508b626b8c8ca70ac11f0d940d403ad35234b26c90422d25762fde423b598695
size 1885
`

**Comment by Asteriska001** [comment]
Ohhhh.I see.Thanks for Your help!😄. 
 By the way,The problem 

> "Once logged in,the page still stayed in the index page..It;s no change.happened."


still bother me.And i think my profile is correct.Did you received the .conf file i sent to you? I set the profile incorrectly?

**Comment by hernantas** [comment]
By no change did you mean no redirect or just no change to the page at all? Can you see the user info on top right corner?

I think your config seems fine.

(Can i make a user in your site to test it?)

**Comment by Asteriska001** [comment]
Emmmm..It's hard to describe the situation. And i can't see the info 😢 .
You could register a user or do what u want to do. It's fine.

**Comment by hernantas** [comment]
Sorry for late reply.

Try to use `curl http://139.129.32.163/public/img/logo48.png`, rather than binary which are what image supposed to be, its text of git.

It mean that your image is not pulled correctly. The reason for that is that this project image is stored not on "code repository" rather than "file repository". `git clone` or `git pull` as far as I know, is just downloading from "code repository". `git lfs pull` instead download files from "file repository" where the image is stored.

**Conclusion:** Use `git lfs pull` to download your image

**Comment by Asteriska001** [comment]
I see.Thank you.
Did you know the reason that caused the "no reaction" after clicking the login button?

**Comment by hernantas** [comment]
I'll look into it. I think its a bug...

**Comment by Asteriska001** [comment]
Fine,Thanks.
